// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtnvjf_162qnpcEi-OME0ksOzzy710WXw',
    appId: '1:229841593204:web:37670a2255db890c9e8221',
    messagingSenderId: '229841593204',
    projectId: 'test-4099a',
    authDomain: 'test-4099a.firebaseapp.com',
    storageBucket: 'test-4099a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaKQ8Q_fBh9eH90uKpjozmBBva3X28_y4',
    appId: '1:229841593204:android:abb6f1da60ed4d829e8221',
    messagingSenderId: '229841593204',
    projectId: 'test-4099a',
    storageBucket: 'test-4099a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiH-AnB9doizeubIScsi3WGkSzmDrsCBs',
    appId: '1:229841593204:ios:b6e826c90fd3b4f99e8221',
    messagingSenderId: '229841593204',
    projectId: 'test-4099a',
    storageBucket: 'test-4099a.appspot.com',
    iosClientId: '229841593204-3j2bopptav9hm4d25d7bbl1q0e70vpm4.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminCitygo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiH-AnB9doizeubIScsi3WGkSzmDrsCBs',
    appId: '1:229841593204:ios:602c4bec055347199e8221',
    messagingSenderId: '229841593204',
    projectId: 'test-4099a',
    storageBucket: 'test-4099a.appspot.com',
    iosClientId: '229841593204-480tmd2dsrjdngtq01f4igv2foo0c3ri.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminCitygo.RunnerTests',
  );
}
